#'  plot mam 7/10
#'  
#'  @description  plots the time series of annual minimum 7 /10 and some statistical tests
#'  
#'  @param mam moving average series generated by MAM function from lfstat.
#'  @param lfobj a low flow time series object produced with ch_lf_obj.
#'  @param n number of days averaged in mam (7 or 10).
#'  
#'  @result a plot of the annual minimum time series annotated with lag-1 correlation and Mann-Kendall trend test
#'  {\item stationid
#'   \item days - number of days averaged in mam
#'   \item mam - series of annual minimum moving averages
#'   \item acf - values from autocorrelation function of mam
#'   \item MK - Mann-Kendall statistics for mam series.
#'   }
#'   
#'  
#'  @import lfstat
#'  
#'  @example 
#'  res <- ch_lf_plot_MAM(mam7, lf_W05AA008, n=7)

ch_lf_plot_MAM <- function (mam, lfobj, n= 7 ) {
    ylabel = paste("Annual ",n, " day minimum daily discharge  (m3/sec)")
  plot(mam, typ="o", lty=3, lwd=0.25,
       xlab= "", ylab = ylabel, las=1,
       ylim = c(0,max(mam[,2])),
       main = attr(lfobj, "lname"),
       pch = 19, col = "darkgreen")
  
  auto <- acf(mam[,2], max.lag=1, plot=FALSE)
  crit05 <- 1.96/sqrt((length(mam7[,2])-1))
  crit01 <- 2.576/sqrt((length(mam7[,2])-1))
  if (auto$acf[2] < crit05) text(min(mam[,1]), 0., paste("lag_1 correlation",round(auto$acf[2],digits =3),"NS"), pos = 4)
  if (auto$acf[2] >= crit05 && auto$acf(2) <= crit01)text(min(mam[,1]), 0., paste("lag_1 correlation",round(auto$acf[2],digits =3),"*"), pos = 4)
  if (auto$acf[2] >= crit01)text(min(mam[,1]), 0., paste("lag_1 correlation",round(auto$acf[2],digits =3),"**"), pos = 4)
    
  mk <- rkt::rkt(mam[ ,1], mam[ , 2])
  fit <- lm(MAn ~ hyear, data <- mam7)
  
  text(max(mam[,1]), 0., paste("MK tau",round(mk$tau,digits =3),"p_value",round(mk$sl, digits=3),
            "Sen's slope", round(mk$B, digits = 5)), pos = 2)
  if(mk$sl <= 0.05) abline(a=fit$coefficients, lty=2, col="darkgreen")
  
  result <- list (attr(lfobj, "station"), n, mam, auto, mk)
  names(result) <- c("station", "days", "mam", "acf", "MK")
  return(result)
}
  
